### PR TITLE
Change EVENT_DEFAULT to EVENT_NONE

### PR DESCRIPTION
**Pull request by robert-lytton**

### CODE REVIEW

**Comment by xross** [comment]
This one is deserving of changelog entry i think (assuming 1.0.0 has been released)

**Comment by robert-lytton** [comment]
The change does not affect the API in any meaningful way.
Only those reading the implementation 'may' notice the indirect clarification.

**Comment by xross** [comment]
Regardless of the whether a comment is required or not  you still need to add a new version to the change log, say 1.0.1 and update module_build_info, otherwise you will be over-writing version 1.0.0 which has been released

**Comment by xross** [comment]
Version bump done.

**Pull request merged**
